### ISSUE TITLE
is os-firewall plugin still relevant ?

### ISSUE THREAD

**Issue by bilalinamdar** [andreas-stuerz/opn-cli#55]
Hi,

I just found your project it is very nice.

I wanted to make Nat and firewall rules (for port opening)
example

Simple Portforward - 8080 > 192.168.0.2:8080
and
Nat - 8080 > 192.168.0.2:80

I found you project but i am still in doubt as it will be compatible with 24.x version of opnsense as it doesn't have os-firewall in plugin section ?

Also guide on how to achive the simple portforward and nat scenario i mentioned.

**Comment by andreas-stuerz** [comment]
Hi bilalinamdar,

the upcoming 2.0 release for opn-cli will be compatible with 24.x.
The Firewall API will be adapted and the source nat feature will be included.

Best regrards,
Andreas
